# StreamGank - VM Development Override
# Use with: docker-compose -f docker-compose.vm-optimized.yml -f docker-compose.vm-dev.yml up
# Now uses optimized unified container for simpler development

services:
    streamgank-app:
        # Development mode optimizations for VM
        volumes:
            # Add source code mounts for development
            - ./ai:/app/ai:cached
            - ./config:/app/config:cached
            - ./utils:/app/utils:cached
            - ./core:/app/core:cached
            - ./database:/app/database:cached
            - ./media:/app/media:cached
            - ./video:/app/video:cached
            - ./main.py:/app/main.py:cached
            # Add GUI source code for development
            - ./gui:/app/gui:cached
        environment:
            - APP_ENV=local
            - NODE_ENV=development
            - LOG_LEVEL=debug
            - PYTHONDONTWRITEBYTECODE=0 # Enable for debugging
        # More resources for development
        deploy:
            resources:
                limits:
                    memory: 4G
                    cpus: "2.0"
        # More frequent health checks for development
        healthcheck:
            interval: 30s
            timeout: 10s
            retries: 2
            start_period: 10s

    redis:
        # Development Redis configuration
        command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru --save ""
        # More logging for development
        logging:
            driver: "json-file"
            options:
                max-size: "25m"
                max-file: "5"

volumes:
    # Override temp volume to use bind mount in development for easier debugging
    streamgank_temp:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${PWD}/temp
